apiVersion: apps/v1
kind: Deployment
metadata:
  name: flink-jobmanager
spec:
  replicas: {{ .Values.jobmanager.replicaCount }}
  selector:
    matchLabels:
      app: flink
      component: jobmanager
  template:
    metadata:
      labels:
        app: flink
        component: jobmanager
    spec:
      initContainers:
      - name: download-hive-connector
        image: alpine:latest
        command: ["/bin/sh", "-c"]
        args:
        - |
          wget -q -O /shared-lib/flink-sql-connector-hive-3.1.3_2.12-1.18.1.jar https://repo1.maven.org/maven2/org/apache/flink/flink-sql-connector-hive-3.1.3_2.12/1.18.1/flink-sql-connector-hive-3.1.3_2.12-1.18.1.jar
          wget -q -O /shared-lib/flink-shaded-hadoop-2-uber-2.8.3-10.0.jar https://repo1.maven.org/maven2/org/apache/flink/flink-shaded-hadoop-2-uber/2.8.3-10.0/flink-shaded-hadoop-2-uber-2.8.3-10.0.jar
          wget -q -O /shared-lib/flink-sql-connector-postgres-cdc-3.1.1.jar https://repo1.maven.org/maven2/org/apache/flink/flink-sql-connector-postgres-cdc/3.1.1/flink-sql-connector-postgres-cdc-3.1.1.jar
        volumeMounts:
        - name: shared-lib
          mountPath: /shared-lib
      containers:
      - name: jobmanager
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args: ["jobmanager"]
        env:
        - name: JOB_MANAGER_RPC_ADDRESS
          value: flink-jobmanager
        - name: FLINK_PROPERTIES
          value: |
            {{- range $key, $value := .Values.flinkConfiguration }}
            {{ $key }}: {{ $value }}
            {{- end }}
        ports:
        - containerPort: 6123
          name: rpc
        - containerPort: 6124
          name: blob-server
        - containerPort: 8081
          name: webui
        - containerPort: 9249
          name: metrics
        resources:
          {{- toYaml .Values.jobmanager.resources | nindent 10 }}
        volumeMounts:
        - name: shared-lib
          mountPath: /opt/flink/usrlib
      volumes:
      - name: shared-lib
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: flink-jobmanager
spec:
  type: LoadBalancer
  ports:
  - name: rpc
    port: 6123
  - name: blob-server
    port: 6124
  - name: webui
    port: 8081
  selector:
    app: flink
    component: jobmanager
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flink-taskmanager
spec:
  replicas: {{ .Values.taskmanager.replicaCount }}
  selector:
    matchLabels:
      app: flink
      component: taskmanager
  template:
    metadata:
      labels:
        app: flink
        component: taskmanager
    spec:
      initContainers:
      - name: download-hive-connector
        image: alpine:latest
        command: ["/bin/sh", "-c"]
        args:
        - |
          wget -q -O /shared-lib/flink-sql-connector-hive-3.1.3_2.12-1.18.1.jar https://repo1.maven.org/maven2/org/apache/flink/flink-sql-connector-hive-3.1.3_2.12/1.18.1/flink-sql-connector-hive-3.1.3_2.12-1.18.1.jar
          wget -q -O /shared-lib/flink-shaded-hadoop-2-uber-2.8.3-10.0.jar https://repo1.maven.org/maven2/org/apache/flink/flink-shaded-hadoop-2-uber/2.8.3-10.0/flink-shaded-hadoop-2-uber-2.8.3-10.0.jar
          wget -q -O /shared-lib/flink-sql-connector-postgres-cdc-3.1.1.jar https://repo1.maven.org/maven2/org/apache/flink/flink-sql-connector-postgres-cdc/3.1.1/flink-sql-connector-postgres-cdc-3.1.1.jar
        volumeMounts:
        - name: shared-lib
          mountPath: /shared-lib
      containers:
      - name: taskmanager
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args: ["taskmanager"]
        env:
        - name: JOB_MANAGER_RPC_ADDRESS
          value: flink-jobmanager
        - name: FLINK_PROPERTIES
          value: |
            {{- range $key, $value := .Values.flinkConfiguration }}
            {{ $key }}: {{ $value }}
            {{- end }}
        ports:
        - containerPort: 9249
          name: metrics
        resources:
          {{- toYaml .Values.taskmanager.resources | nindent 10 }}
        volumeMounts:
        - name: shared-lib
          mountPath: /opt/flink/usrlib
      volumes:
      - name: shared-lib
        emptyDir: {}
