apiVersion: apps/v1
kind: Deployment
metadata:
  name: hive-metastore
  namespace: lakehouse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hive-metastore
  template:
    metadata:
      labels:
        app: hive-metastore
    spec:
      containers:
      - name: hive-metastore
        image: bitsondatadev/hive-metastore:latest
        env:
        - name: DB_DRIVER
          value: "postgres"
        - name: DB_URL
          value: "jdbc:postgresql://hive-db-postgresql:5432/metastore"
        - name: DB_USER
          value: "hive"
        - name: DB_PASS
          value: "password123"
        ports:
        - containerPort: 9083
          name: thrift
        resources:
          limits:
            memory: 800Mi
          requests:
            memory: 400Mi
---
apiVersion: v1
kind: Service
metadata:
  name: hive-metastore
  namespace: lakehouse
spec:
  selector:
    app: hive-metastore
  ports:
  - port: 9083
    targetPort: 9083
    name: thrift
