from datetime import datetime, timedelta

from airflow import DAG
from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
from kubernetes.client import models as k8s

DEFAULT_PACKAGES = (
    "org.apache.iceberg:iceberg-spark-runtime-3.5_2.12:1.5.2,"
    "org.apache.hadoop:hadoop-aws:3.3.4,"
    "com.amazonaws:aws-java-sdk-bundle:1.12.262"
)

SPARK_CONF = [
    "--conf", "spark.sql.catalog.iceberg=org.apache.iceberg.spark.SparkCatalog",
    "--conf", "spark.sql.catalog.iceberg.type=hive",
    "--conf", "spark.sql.catalog.iceberg.uri=thrift://hive-metastore.lakehouse.svc.cluster.local:9083",
    "--conf", "spark.sql.catalog.iceberg.warehouse=s3a://lakehouse/lakehouse/",
    "--conf", "spark.hadoop.fs.s3a.endpoint=http://minio.lakehouse.svc.cluster.local:9000",
    "--conf", "spark.hadoop.fs.s3a.access.key=admin",
    "--conf", "spark.hadoop.fs.s3a.secret.key=password123",
    "--conf", "spark.hadoop.fs.s3a.path.style.access=true",
    "--conf", "spark.hadoop.fs.s3a.impl=org.apache.hadoop.fs.s3a.S3AFileSystem",
    "--conf", "spark.sql.extensions=org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions",
    "--conf", "spark.sql.shuffle.partitions=6",
    "--conf", "spark.jars.ivy=/tmp/.ivy",
    "--conf", "spark.driver.extraJavaOptions=-Divy.cache.dir=/tmp/.ivy/cache -Djava.net.preferIPv4Stack=true",
    "--conf", "spark.executor.extraJavaOptions=-Djava.net.preferIPv4Stack=true",
    "--conf", "spark.driver.host=$(SPARK_LOCAL_IP)",
]

SPARK_BASE_ARGS = [
    "--master", "spark://spark-master:7077",
    "--deploy-mode", "client",
    "--packages", DEFAULT_PACKAGES,
    "--executor-cores", "1",
    "--executor-memory", "512m",
    "--driver-memory", "512m",
    "--total-executor-cores", "3",
] + SPARK_CONF

JOB_VOLUME = k8s.V1Volume(
    name="spark-batch-jobs",
    config_map=k8s.V1ConfigMapVolumeSource(name="spark-batch-jobs"),
)
JOB_VOLUME_MOUNT = k8s.V1VolumeMount(
    name="spark-batch-jobs",
    mount_path="/opt/spark/jobs",
    read_only=True,
)

IVY_VOLUME = k8s.V1Volume(
    name="spark-ivy-cache",
    persistent_volume_claim=k8s.V1PersistentVolumeClaimVolumeSource(claim_name="spark-ivy-pvc"),
)
IVY_VOLUME_MOUNT = k8s.V1VolumeMount(
    name="spark-ivy-cache",
    mount_path="/tmp/.ivy",
)

default_args = {
    "owner": "data-platform",
    "depends_on_past": False,
    "retries": 1,
    "retry_delay": timedelta(minutes=5),
}

with DAG(
    dag_id="server_monitoring_hourly_kpi",
    default_args=default_args,
    description="Aggregate raw server metrics into Iceberg gold KPI table every hour.",
    schedule="0 * * * *",
    start_date=datetime(2026, 1, 1),
    catchup=False,
    max_active_runs=1,
    tags=["lakehouse", "spark", "batch"],
) as dag:
    KubernetesPodOperator(
        task_id="aggregate_kpi_summary",
        namespace="orchestration",
        image="apache/spark:3.5.1",
        cmds=["/opt/spark/bin/spark-submit"],
        arguments=SPARK_BASE_ARGS
        + ["/opt/spark/jobs/server_monitoring_kpi_batch.py", "--lookback-hours", "1"],
        volumes=[JOB_VOLUME, IVY_VOLUME],
        volume_mounts=[JOB_VOLUME_MOUNT, IVY_VOLUME_MOUNT],
        env_vars=[
            k8s.V1EnvVar(name="SPARK_MASTER_PORT", value="7077"),
            k8s.V1EnvVar(
                name="SPARK_LOCAL_IP",
                value_from=k8s.V1EnvVarSource(
                    field_ref=k8s.V1ObjectFieldSelector(field_path="status.podIP")
                ),
            ),
        ],
        container_resources=k8s.V1ResourceRequirements(
            requests={"cpu": "100m", "memory": "512Mi"},
            limits={"cpu": "500m", "memory": "1024Mi"},
        ),
        get_logs=True,
        is_delete_operator_pod=True,
        in_cluster=True,
    )

with DAG(
    dag_id="server_monitoring_daily_compaction",
    default_args=default_args,
    description="Compact small Iceberg files generated by realtime writes.",
    schedule="0 0 * * *",
    start_date=datetime(2026, 1, 1),
    catchup=False,
    max_active_runs=1,
    tags=["lakehouse", "spark", "maintenance"],
) as dag:
    KubernetesPodOperator(
        task_id="compact_raw_sftp_table",
        namespace="orchestration",
        image="apache/spark:3.5.1",
        cmds=["/opt/spark/bin/spark-submit"],
        arguments=SPARK_BASE_ARGS + ["/opt/spark/jobs/iceberg_compaction.py"],
        volumes=[JOB_VOLUME, IVY_VOLUME],
        volume_mounts=[JOB_VOLUME_MOUNT, IVY_VOLUME_MOUNT],
        env_vars=[
            k8s.V1EnvVar(name="SPARK_MASTER_PORT", value="7077"),
            k8s.V1EnvVar(
                name="SPARK_LOCAL_IP",
                value_from=k8s.V1EnvVarSource(
                    field_ref=k8s.V1ObjectFieldSelector(field_path="status.podIP")
                ),
            ),
        ],
        container_resources=k8s.V1ResourceRequirements(
            requests={"cpu": "100m", "memory": "512Mi"},
            limits={"cpu": "500m", "memory": "1024Mi"},
        ),
        get_logs=True,
        is_delete_operator_pod=True,
        in_cluster=True,
    )
