# Minio Official Image Configuration
global:
  security:
    allowInsecureImages: true
mode: standalone
image:
  registry: docker.io
  repository: minio/minio
  tag: latest

# Overwrite command/args to work with official image
command: ["/bin/sh", "-ce"]
args: ["mkdir -p /data && minio server /data --console-address :9001"]

auth:
  rootUser: admin
  rootPassword: password123

console:
  enabled: false

extraEnvVars:
  - name: MINIO_ROOT_USER
    value: "admin"
  - name: MINIO_ROOT_PASSWORD
    value: "password123"
  - name: MINIO_BROWSER
    value: "on"

service:
  type: LoadBalancer
  ports:
    api: 9000
    console: 9001

resources:
  limits:
    memory: 512Mi
  requests:
    memory: 256Mi
