# Kafka Apache Image Configuration
global:
  security:
    allowInsecureImages: true
replicaCount: 1
image:
  registry: docker.io
  repository: apache/kafka
  tag: latest

# Simple KRaft for local dev
kraft:
  enabled: true
zookeeper:
  enabled: false

persistence:
  size: 2Gi

resources:
  limits:
    memory: 768Mi
  requests:
    memory: 512Mi

# Overwrite entrypoint for official image if needed
# but apache/kafka:latest works well with standard envs
