# Kafka KRaft Configuration (No ZooKeeper)
global:
  security:
    allowInsecureImages: true
replicaCount: 3
image:
  registry: public.ecr.aws
  repository: bitnami/kafka
  tag: latest

# Kích hoạt KRaft
kraft:
  enabled: true

# Tắt ZooKeeper để tiết kiệm tài nguyên
zookeeper:
  enabled: false

persistence:
  size: 5Gi

# Điều chỉnh tài nguyên cho máy 16GB RAM
resources:
  limits:
    memory: 768Mi
  requests:
    memory: 512Mi

# Tối ưu JVM heap size (quan trọng để tránh OOM)
heapOpts: "-Xmx512M -Xms512M"

# Cho phép truy cập từ bên ngoài
externalAccess:
  enabled: false
