apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spark-ivy-pvc
  namespace: orchestration
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 2Gi
